apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: stock-mesh
  labels:
    app: payment-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        version: v1
    spec:
      containers:
        - name: payment-service
          image: payment-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: CHAOS_MODE
              value: "off"
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: stock-mesh
spec:
  selector:
    app: payment-service
  ports:
    - port: 3002
      targetPort: 3002
